name: iot-labs-uc-test
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Test of Ubuntu Core w/ gcloud IoT Core integration 
description: |
  Test snap for Ubuntu Core on a Raspberry Pi 3b+.
  Attempt to read gpio and publish telemetry to Google Cloud Iot Core via
  MQTT bridge.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  hello:
    command: bin/hello
parts:
  gnu-hello:
    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
    plugin: autotools
