name: iot-labs-uc-test
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Test of Ubuntu Core with gcloud IoT Core integration 
description: |
  Test snap for Ubuntu Core on a Raspberry Pi 3b+.
  Attempt to read gpio and publish telemetry to Google Cloud PubSub.
  Test various aspects of snap development.
grade: devel # or 'stable'
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: armhf
    run-on: armhf

#hooks:
#  install:
#    plugs: [home]

apps:
  iot-labs-uc-test:
    command: aatelemetry
    # daemon: simple
    plugs: [gpio-memory-control, home, network] 

parts:
  aatelemetry:
    source: .
    plugin: python
    python-version: python3
    python-packages: [gpiozero, google-cloud-pubsub==0.39.1]
    #override-build: |
      #make test
      #mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      #cp test $SNAPCRAFT_PART_INSTALL/bin/test

#passthrough:
#  layout:
#    /home/haakonsbakken/pubsubcredentials.json:
#      bind-file: $SNAP_DATA/pubsubcredentials.json