name: iot-labs-uc-test
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Test of Ubuntu Core with gcloud IoT Core integration 
description: |
  Test snap for Ubuntu Core on a Raspberry Pi 3b+.
  Attempt to read gpio and publish telemetry to Google Cloud Iot Core via
  MQTT bridge.

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: armhf
    run-on: armhf

apps:
  iot-labs-uc-test:
    command: test
    # daemon: simple
    plugs: [gpio-memory-control] 

parts:
  testpart:
    plugin: python
    python-version: python3
    python-packages: [RPi.GPIO]
    source: .
